// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmxwPjKNB0ZndFnBsDc5oreqGIcbkdkdU',
    appId: '1:449267115764:web:75e72a4f57bc7b83b8a0a1',
    messagingSenderId: '449267115764',
    projectId: 'fso-89bc5',
    authDomain: 'fso-89bc5.firebaseapp.com',
    storageBucket: 'fso-89bc5.appspot.com',
    measurementId: 'G-3LLCK4XK5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrHagTWD_IuTVD0Fd2XPGSBxN-21vze2Q',
    appId: '1:449267115764:android:b6b30001f58ce0fcb8a0a1',
    messagingSenderId: '449267115764',
    projectId: 'fso-89bc5',
    storageBucket: 'fso-89bc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB--iHs8qRmLwPEDgm8Q0xXvZdgj7s5ZA',
    appId: '1:449267115764:ios:0beb722f656547f1b8a0a1',
    messagingSenderId: '449267115764',
    projectId: 'fso-89bc5',
    storageBucket: 'fso-89bc5.appspot.com',
    iosBundleId: 'com.example.fso',
  );
}
